### ISSUE TITLE
where to find admin auth ?

### ISSUE THREAD

**Issue by todokku** [vinothsundararajan/Django_Blog#2]
Hi Vinoth,
im runnug my own blog on heroku work fine :
https://weblogeman.herokuapp.com
admin cp : 
https://weblogeman.herokuapp.com/admin/login/?next=/admin/
  question is : where to find admin auth ? user & pass ?
waiting for your response
finest regards
goodbye

**Comment by vinothsundararajan** [comment]
You have to create superuser using below commands form your project directory:

**heroku run python blog/manage.py createsuperuser
Running python blog/manage.py createsuperuser on ⬢ manlinux... up, run.5013 (Free)
Username (leave blank to use 'u37167'): 
Password:
confirm password:**

once you have created, you will be able to access admin page
https://weblogeman.herokuapp.com/admin/login/

with your super user.
Happy Blogging.
